### ISSUE TITLE
Standard comments cause TypeError on jsonData.ctx.type in pmd.js

### ISSUE THREAD

**Issue by alexhafner** [OraOpenSource/plsql-md-doc#30]
If you have "standard" comments in your procedural code, processing fails with 

```
...pmd.js:84
        type: jsonData.ctx.type,
                          ^

TypeError: Cannot read property 'type' of undefined
    at /Users/alexhafner/git/plsql-md-doc/lib/pmd.js:84:27
    at Array.forEach (native)
    at Object.pmd.processFile (/Users/alexhafner/git/plsql-md-doc/lib/pmd.js:69:16)
    at /Users/alexhafner/git/plsql-md-doc/lib/pmd.js:279:24
    at Array.forEach (native)
    at Object.pmd.generateData (/Users/alexhafner/git/plsql-md-doc/lib/pmd.js:239:18)
    at Object.<anonymous> (/Users/alexhafner/git/plsql-md-doc/app.js:87:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

This also happens when the ! is added in order to ignore the comments blog, examples:

```
/*
Standard Comment 
*/

/*!
Standard Comment 
*/

/* Standard Comment */
```

A sample file is attached.

The expected behaviour would be that we only parse comments with /\* and not /**. A side issue may be that a lot of PL/SQL code has got decorative frames like so

```
/****************************************************************************
 *                                                                          *
 *                           I love ASCII                                   *
 *                                                                          *
 ****************************************************************************
 */
```

I think javadoc just ignores those, it would be good if plsql-md-doc did the same.
[pmd2.txt](https://github.com/OraOpenSource/plsql-md-doc/files/265983/pmd2.txt)

**Comment by martindsouza** [comment]
Thanks @rimblas for the fix.
