### ISSUE TITLE
error running applicaton

### ISSUE THREAD

**Issue by hg-smart** [OraOpenSource/plsql-md-doc#31]
```
[oracle@ODIGettingStarted plsql-md-doc]$ node app myProject
/home/oracle/dev/plsql-md-doc/lib/pmd.js:84
        type: jsonData.ctx.type,
                          ^

TypeError: Cannot read property 'type' of undefined
    at /home/oracle/dev/plsql-md-doc/lib/pmd.js:84:27
    at Array.forEach (native)
    at Object.pmd.processFile (/home/oracle/dev/plsql-md-doc/lib/pmd.js:69:16)
    at /home/oracle/dev/plsql-md-doc/lib/pmd.js:279:24
    at Array.forEach (native)
    at Object.pmd.generateData (/home/oracle/dev/plsql-md-doc/lib/pmd.js:239:18)
    at Object.<anonymous> (/home/oracle/dev/plsql-md-doc/app.js:87:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
[oracle@ODIGettingStarted plsql-md-doc]$ 

```

**Comment by hg-smart** [comment]
happens only when no javadoc available in any file

**Comment by martindsouza** [comment]
@hg-smart Did you resolve your issue?

**Comment by hg-smart** [comment]
just let the code run over all projects packages file and of course no javadoc, only svn tags was available. As soon as at least one package file has a javadoc entry applications runs fine.
