### ISSUE TITLE
TypeError: markdown is not a function

### ISSUE THREAD

**Issue by palmaguer** [OraOpenSource/plsql-md-doc#84]
## System Summary
```
   System Version:      22G91
   Hardware Model:      MacBookPro18,3
```

## Error Message

```
/Users/generic/dev/plsql-md-doc/node_modules/dox/lib/dox.js:249
    description.full = markdown(description.full);
                       ^

TypeError: markdown is not a function
    at exports.parseComment (/Users/palmaguer/dev/plsql-md-doc/node_modules/dox/lib/dox.js:249:24)
    at exports.parseComments (/Users/palmaguer/dev/plsql-md-doc/node_modules/dox/lib/dox.js:112:25)
    at pmd.processFile (/Users/palmaguer/dev/plsql-md-doc/lib/pmd.js:93:22)
    at pmd.readFolder (/Users/palmaguer/dev/plsql-md-doc/lib/pmd.js:382:22)
    at /Users/palmaguer/dev/plsql-md-doc/lib/pmd.js:457:9
    at Array.forEach (<anonymous>)
    at pmd.generateData (/Users/palmaguer/dev/plsql-md-doc/lib/pmd.js:456:18)
    at Object.<anonymous> (/Users/palmaguer/dev/plsql-md-doc/app.js:87:16)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.17.1
```

**Comment by martindsouza** [comment]
@pablodaniel03 thanks for posting the issue. I'm not supporting this project anymore so unfortunately you'll need to debug on your own.

That said just reading the issue `dox.js` is from https://github.com/tj/dox Perhaps you can see if there's a newer version or a different library that's compatible.

**Comment by jifbrodeur** [comment]
Hi @pablodaniel03 @martindsouza, the solution is rather simple, before running npm install change the package.json to resolve the dependencies issue, and changing the line for dox with the following: "dox": "^1.0.0", 
Martin if I fork the repo and do a PR would you merge the change?
